login_page: # Optional
  title: "Login to Foobar" # Optional, defaults to "Login"
  dump_users: true # Optional, defaults to false
  description: | # Optional, defaults to empty string
    **This is a test IdP**
    
    This is a _test_ of [Markdown](https://github.com/gomarkdown/markdown) rendering.

services: # Required
  - entity_id: "saml-test-sp" # Required
    assertion_consumer_service: "http://localhost:9009/saml/acs" # Required

users: # Required
  - username: "test" # Required
    email: "test@test.com" # Required
    password: "test" # Required
    first_name: "Test" # Required
    last_name: "User" # Required
    groups: # Optional
      - "foobar"
      - "baz"
