on:
  push:
    tags:
      - "v*"

jobs:
  release:
    if: ${{ github.repository_owner == 'derekmckinnon' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: docker/setup-buildx-action@v1

      - uses: docker/setup-qemu-action@v1

      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.output.tags }}
          platforms: linux/amd64,linux/arm64
